# Generated by Django 5.2.7 on 2025-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('type_of_usg', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special')], default='Normal', max_length=50)),
                ('referred_by', models.CharField(max_length=200)),
                ('sonologist', models.CharField(max_length=200)),
                ('total_ultra', models.PositiveSmallIntegerField(default=1)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'referred_by', 'sonologist'], name='reports_rep_date_54d601_idx')],
            },
        ),
    ]
