# Generated by Django 5.2.7 on 2025-10-23 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('exam_type', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special')], default='Normal', max_length=50)),
                ('total_ultra', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exam_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='masterdata.examname')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='masterdata.referrer')),
                ('sonologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='masterdata.sonologist')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reports_rep_date_ed01c3_idx')],
            },
        ),
    ]
