# Generated by Django 5.2.7 on 2025-10-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='type_of_usg',
            new_name='exam_type',
        ),
        migrations.AddField(
            model_name='report',
            name='exam_name',
            field=models.CharField(choices=[('Abdomen', 'Abdomen'), ('KUB', 'KUB'), ('TVS', 'TVS'), ('Obstetric', 'Obstetric')], default='Abdomen', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='referred_by',
            field=models.CharField(choices=[('Prof. Dr. Mahbubul Islam Majumder', 'Prof. Dr. Mahbubul Islam Majumder'), ('Prof. Dr. Samsun Nahar', 'Prof. Dr. Samsun Nahar'), ('Prof. Dr. Haroon-Or-Rashid', 'Prof. Dr. Haroon-Or-Rashid'), ('Dr. Belal Hossain', 'Dr. Belal Hossain'), ('Prof. Dr. Md. Safiqur Rahman Patwary', 'Prof. Dr. Md. Safiqur Rahman Patwary'), ('Prof. Dr. Nasir Uddin Mahmud', 'Prof. Dr. Nasir Uddin Mahmud'), ('Dr. Mahfuzur Rahman (EMON)', 'Dr. Mahfuzur Rahman (EMON)'), ('Dr. Hasan Imam (Sany)', 'Dr. Hasan Imam (Sany)'), ('Dr. Joynal Abedin', 'Dr. Joynal Abedin'), ('Dr. Md. Mainul Hasan Sohel', 'Dr. Md. Mainul Hasan Sohel'), ('Dr. Kawsar Hamid', 'Dr. Kawsar Hamid'), ('Dr. Mostaque Ahmad', 'Dr. Mostaque Ahmad'), ('Dr. Shamsul Islam (Bokol)', 'Dr. Shamsul Islam (Bokol)'), ('Dr. Nazim Uddin', 'Dr. Nazim Uddin'), ('Dr. Md. Shahid Ullah', 'Dr. Md. Shahid Ullah'), ('Dr. Jasrin Akter Milli', 'Dr. Jasrin Akter Milli'), ('Dr. Shahnaz Parvin Zeba', 'Dr. Shahnaz Parvin Zeba'), ('Dr. Salma Akter Ripa', 'Dr. Salma Akter Ripa'), ('Dr. Risana Akter', 'Dr. Risana Akter'), ('Dr. Nabila Binte Ali', 'Dr. Nabila Binte Ali'), ('Prof. Dr. Zahirul Alam', 'Prof. Dr. Zahirul Alam'), ('Dr. Habibur Rahman', 'Dr. Habibur Rahman'), ('Dr. Arifur Rahman', 'Dr. Arifur Rahman'), ('Dr. Sayeda Nafiz Jobaida', 'Dr. Sayeda Nafiz Jobaida'), ('Dr. Emdadul Hoque', 'Dr. Emdadul Hoque'), ('Dr. Ashraful Hoque', 'Dr. Ashraful Hoque'), ('Dr. Rifat Chow. Anik', 'Dr. Rifat Chow. Anik'), ('Dr. Saiful Hoque', 'Dr. Saiful Hoque'), ('Dr. Abul Khair', 'Dr. Abul Khair'), ('Dr. Shahadat Billa', 'Dr. Shahadat Billa'), ('Dr. Masud EMO', 'Dr. Masud EMO'), ('Dr. Nasid Hasan Mollah EMO', 'Dr. Nasid Hasan Mollah EMO'), ('Dr. Saikot EMO', 'Dr. Saikot EMO'), ('Dr. Anirban Roy EMO', 'Dr. Anirban Roy EMO'), ('Upazilla Health Complex', 'Upazilla Health Complex'), ('Self', 'Self')], default='Self', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='sonologist',
            field=models.CharField(choices=[('Dr. Nur Mohammad', 'Dr. Nur Mohammad'), ('Dr. Nabila Binte Ali', 'Dr. Nabila Binte Ali'), ('Dr. Saikot', 'Dr. Saikot')], default='Dr. Nur Mohammad', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_ultra',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
    ]
