# Generated by Django 5.2.7 on 2025-10-29 05:44

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='referred_by',
            field=models.ForeignKey(blank=True, default=reports.models.Report.get_self_referrer, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='masterdata.referrer'),
        ),
    ]
