# Generated by Django 5.2.7 on 2025-10-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_type_of_usg_report_exam_type_report_exam_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='exam_name',
            field=models.CharField(choices=[('Whole Abdomen', 'Whole Abdomen'), ('Whole Abdomen with Pregnancy', 'Whole Abdomen with Pregnancy'), ('Lower Abdomen', 'Lower Abdomen'), ('HBS', 'HBS'), ('Pregnancy Profile', 'Pregnancy Profile'), ('Pregnancy Profile twin', 'Pregnancy Profile twin'), ('Anomaly Scan', 'Anomaly Scan'), ('Fetal Doppler Study', 'Fetal Doppler Study'), ('Thyroid/Neck', 'Thyroid/Neck'), ('Testes/ISR', 'Testes/ISR'), ('Swelling', 'Swelling')], default='Abdomen', max_length=100),
        ),
    ]
