# Generated by Django 5.2.7 on 2025-11-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('reports', '0002_alter_report_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='masterdata.examtype'),
        ),
    ]
